# Generated by Django 6.0 on 2025-12-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('area', models.CharField(choices=[('FISCAL', 'Fiscal'), ('CONTABLE', 'Contable'), ('IT', 'IT'), ('SOPORTE', 'Soporte General')], max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
