# Generated by Django 6.0.2 on 2026-02-13 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documento',
        ),
    ]
