# Generated by Django 6.0 on 2025-12-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_consultacontacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultacontacto',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
