# Generated by Django 6.0.2 on 2026-03-10 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clienteempresa',
            options={'verbose_name': 'Vínculo Cliente-Empresa', 'verbose_name_plural': 'Vínculos Cliente-Empresa'},
        ),
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['-fecha_subida']},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clienteempresa',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='clienteempresa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_vinculados', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='clienteempresa',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('DUENO', 'Dueño'), ('GERENTE_FINANCIERO', 'Gerente Financiero'), ('RRHH', 'Recursos Humanos'), ('OTRO', 'Otro')], default='OTRO', max_length=50),
        ),
    ]
