# Generated by Django 6.0.2 on 2026-03-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_clienteempresa_options_alter_documento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('importante', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Novedades',
                'ordering': ['-fecha'],
            },
        ),
    ]
