# Generated by Django 6.0.2 on 2026-03-16 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_novedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='core.empresa'),
            preserve_default=False,
        ),
    ]
