# Generated by Django 6.0.2 on 2026-03-10 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documento',
        ),
    ]
